export interface StoreItem {
    id: number;
    name: string;
    price: number;
    description: string;
    thumbnailImageUrl: string;
    imageUrl: string;
}

export const STORE_ITEMS: StoreItem[] = [
  {
    id: 1291,
    name: 'Laundry Detergent',
    price: 473.1,
    description:
      'A high-quality laundry detergent sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1755,
    name: 'Frozen Pizza',
    price: 425.48,
    description: 'A high-quality frozen pizza sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6721,
    name: 'Chicken Nuggets',
    price: 299.83,
    description:
      'A high-quality chicken nuggets sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8585,
    name: 'Lemons',
    price: 50.98,
    description: 'A high-quality lemons sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6444,
    name: 'Honey',
    price: 365.58,
    description: 'A high-quality honey sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6824,
    name: 'Vodka',
    price: 464.15,
    description: 'A high-quality vodka sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3117,
    name: 'Soft Drinks',
    price: 215.69,
    description: 'A high-quality soft drinks sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5874,
    name: 'Orange Juice',
    price: 27.55,
    description: 'A high-quality orange juice sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4354,
    name: 'Maple Syrup',
    price: 38.67,
    description: 'A high-quality maple syrup sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9583,
    name: 'Butter',
    price: 189.82,
    description: 'A high-quality butter sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7972,
    name: 'Garlic',
    price: 297.57,
    description: 'A high-quality garlic sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9878,
    name: 'Onions',
    price: 206.43,
    description: 'A high-quality onions sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9479,
    name: 'Carrots',
    price: 356.44,
    description: 'A high-quality carrots sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3828,
    name: 'Blueberries',
    price: 203.7,
    description: 'A high-quality blueberries sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7577,
    name: 'Cucumber',
    price: 387.83,
    description: 'A high-quality cucumber sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1076,
    name: 'Canned Beans',
    price: 263.75,
    description: 'A high-quality canned beans sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6089,
    name: 'Eggs',
    price: 340.25,
    description: 'A high-quality eggs sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6654,
    name: 'Tea',
    price: 103.6,
    description: 'A high-quality tea sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6010,
    name: 'Frozen Vegetables',
    price: 55.22,
    description:
      'A high-quality frozen vegetables sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9600,
    name: 'Salt',
    price: 191.69,
    description: 'A high-quality salt sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 2872,
    name: 'Bottled Water',
    price: 242.15,
    description:
      'A high-quality bottled water sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6301,
    name: 'Sardines',
    price: 295.23,
    description: 'A high-quality sardines sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3273,
    name: 'Mustard',
    price: 366.7,
    description: 'A high-quality mustard sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6501,
    name: 'Beef',
    price: 447.57,
    description: 'A high-quality beef sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5543,
    name: 'Granola Bars',
    price: 193.27,
    description: 'A high-quality granola bars sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1005,
    name: 'Lettuce',
    price: 389.33,
    description: 'A high-quality lettuce sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5507,
    name: 'Pepper',
    price: 472.22,
    description: 'A high-quality pepper sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3204,
    name: 'Ketchup',
    price: 361.16,
    description: 'A high-quality ketchup sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3360,
    name: 'Bell Peppers',
    price: 145.17,
    description: 'A high-quality bell peppers sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8974,
    name: 'Soup',
    price: 404.74,
    description: 'A high-quality soup sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6598,
    name: 'Flour',
    price: 22.02,
    description: 'A high-quality flour sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7248,
    name: 'Macaroni and Cheese',
    price: 486.08,
    description:
      'A high-quality macaroni and cheese sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6206,
    name: 'Spinach',
    price: 407.27,
    description: 'A high-quality spinach sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7527,
    name: 'Potatoes',
    price: 205.23,
    description: 'A high-quality potatoes sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5012,
    name: 'Shrimp',
    price: 133.62,
    description: 'A high-quality shrimp sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9951,
    name: 'Chips',
    price: 409.64,
    description: 'A high-quality chips sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 2364,
    name: 'Broth',
    price: 80.71,
    description: 'A high-quality broth sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5719,
    name: 'Cheese',
    price: 247.95,
    description: 'A high-quality cheese sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4630,
    name: 'Beer',
    price: 218.61,
    description: 'A high-quality beer sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3986,
    name: 'Fish',
    price: 90.99,
    description: 'A high-quality fish sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5964,
    name: 'Canola Oil',
    price: 148.8,
    description: 'A high-quality canola oil sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1593,
    name: 'Toothpaste',
    price: 270.36,
    description: 'A high-quality toothpaste sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7338,
    name: 'Conditioner',
    price: 4.26,
    description: 'A high-quality conditioner sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8000,
    name: 'Cookies',
    price: 419.77,
    description: 'A high-quality cookies sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1299,
    name: 'Gin',
    price: 4.72,
    description: 'A high-quality gin sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 2014,
    name: 'Coffee',
    price: 24.56,
    description: 'A high-quality coffee sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3394,
    name: 'Chewing Gum',
    price: 487.59,
    description: 'A high-quality chewing gum sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6850,
    name: 'Energy Drinks',
    price: 157.41,
    description:
      'A high-quality energy drinks sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7726,
    name: 'Raisins',
    price: 72.69,
    description: 'A high-quality raisins sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6967,
    name: 'Dish Soap',
    price: 205.72,
    description: 'A high-quality dish soap sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7103,
    name: 'Limes',
    price: 210.96,
    description: 'A high-quality limes sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1958,
    name: 'Mushrooms',
    price: 125.06,
    description: 'A high-quality mushrooms sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8710,
    name: 'Hot Dogs',
    price: 48.21,
    description: 'A high-quality hot dogs sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5734,
    name: 'Vinegar',
    price: 402.56,
    description: 'A high-quality vinegar sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9666,
    name: 'Tortillas',
    price: 322.9,
    description: 'A high-quality tortillas sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 2226,
    name: 'Peanut Butter',
    price: 227.39,
    description:
      'A high-quality peanut butter sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9740,
    name: 'Hummus',
    price: 426.94,
    description: 'A high-quality hummus sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4186,
    name: 'Jam',
    price: 366.43,
    description: 'A high-quality jam sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3448,
    name: 'Shampoo',
    price: 68.8,
    description: 'A high-quality shampoo sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7797,
    name: 'Tomatoes',
    price: 175.01,
    description: 'A high-quality tomatoes sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 2295,
    name: 'Yogurt',
    price: 398.96,
    description: 'A high-quality yogurt sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6717,
    name: 'Pickles',
    price: 174.13,
    description: 'A high-quality pickles sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3542,
    name: 'Toilet Paper',
    price: 120.02,
    description: 'A high-quality toilet paper sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3449,
    name: 'Sugar',
    price: 476.42,
    description: 'A high-quality sugar sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1883,
    name: 'Pancake Mix',
    price: 109.74,
    description: 'A high-quality pancake mix sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6647,
    name: 'Bagels',
    price: 224.5,
    description: 'A high-quality bagels sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7369,
    name: 'Wine',
    price: 372.16,
    description: 'A high-quality wine sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3718,
    name: 'Bread',
    price: 370.11,
    description: 'A high-quality bread sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8024,
    name: 'Pasta Sauce',
    price: 78.29,
    description: 'A high-quality pasta sauce sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8559,
    name: 'Olive Oil',
    price: 71.19,
    description: 'A high-quality olive oil sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1925,
    name: 'Cashews',
    price: 145.3,
    description: 'A high-quality cashews sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1607,
    name: 'Salsa',
    price: 175.22,
    description: 'A high-quality salsa sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 2200,
    name: 'Chicken Breast',
    price: 446.48,
    description:
      'A high-quality chicken breast sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8346,
    name: 'Almonds',
    price: 23.95,
    description: 'A high-quality almonds sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6258,
    name: 'Milk',
    price: 458.88,
    description: 'A high-quality milk sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1560,
    name: 'Soap',
    price: 322.97,
    description: 'A high-quality soap sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6564,
    name: 'Oatmeal',
    price: 43.05,
    description: 'A high-quality oatmeal sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1723,
    name: 'Trail Mix',
    price: 263.82,
    description: 'A high-quality trail mix sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6477,
    name: 'Ice Cream',
    price: 97.04,
    description: 'A high-quality ice cream sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 9602,
    name: 'French Fries',
    price: 169.13,
    description: 'A high-quality french fries sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6988,
    name: 'Bananas',
    price: 420.85,
    description: 'A high-quality bananas sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8032,
    name: 'Donuts',
    price: 110.8,
    description: 'A high-quality donuts sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4741,
    name: 'Grapes',
    price: 377.54,
    description: 'A high-quality grapes sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4403,
    name: 'Canned Corn',
    price: 482.86,
    description: 'A high-quality canned corn sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6980,
    name: 'Waffles',
    price: 462.72,
    description: 'A high-quality waffles sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3110,
    name: 'Guacamole',
    price: 302.48,
    description: 'A high-quality guacamole sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5291,
    name: 'Pasta',
    price: 428.81,
    description: 'A high-quality pasta sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8228,
    name: 'Soy Sauce',
    price: 311.85,
    description: 'A high-quality soy sauce sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 3620,
    name: 'Strawberries',
    price: 159.89,
    description: 'A high-quality strawberries sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8081,
    name: 'Pork',
    price: 492.18,
    description: 'A high-quality pork sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4052,
    name: 'Chocolate',
    price: 438.32,
    description: 'A high-quality chocolate sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 6579,
    name: 'Tuna',
    price: 196.56,
    description: 'A high-quality tuna sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 8583,
    name: 'Paper Towels',
    price: 148.92,
    description: 'A high-quality paper towels sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7534,
    name: 'Cereal',
    price: 336.27,
    description: 'A high-quality cereal sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 5056,
    name: 'Walnuts',
    price: 356.44,
    description: 'A high-quality walnuts sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1280,
    name: 'Whiskey',
    price: 187.39,
    description: 'A high-quality whiskey sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 1385,
    name: 'Apples',
    price: 139.31,
    description: 'A high-quality apples sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7762,
    name: 'Sausages',
    price: 457.18,
    description: 'A high-quality sausages sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 7204,
    name: 'Rum',
    price: 69.8,
    description: 'A high-quality rum sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
  {
    id: 4916,
    name: 'Rice',
    price: 87.06,
    description: 'A high-quality rice sourced for freshness and value.',
    imageUrl: 'https://placehold.co/300',
    thumbnailImageUrl: 'https://placehold.co/50',
  },
];

export const STORE_ITEMS_SORTED = STORE_ITEMS.sort((a, b) => {
  if (a.name < b.name) {
    return -1;
  }
  if (a.name > b.name) {
    return 1;
  }
  return 0;
})